// Reads every docs/BayMax/skills/*/SKILL.md and regenerates src/lib/max/skills.generated.ts.
// Run: node --experimental-strip-types scripts/build-skills.ts
//
// Mirrors the pattern scripts/scrape-prereqs.ts uses for src/data/prereqs.ts: a generated data
// module, not a runtime fs.readFileSync — Vercel's Node builder traces code imports fine but
// arbitrary non-code files reached via fs are exactly the kind of thing that already broke
// production once (see CLAUDE.md's ".js"-extension convention section). Re-run this whenever a
// SKILL.md changes; nothing reads the markdown files at runtime.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SKILLS_DIR = join(import.meta.dirname, '../docs/BayMax/skills')
const OUT_FILE = join(import.meta.dirname, '../src/lib/max/skills.generated.ts')

interface ParsedSkill {
  name: string
  description: string
  instructions: string
}

function parseSkillMd(raw: string, dirName: string): ParsedSkill {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!match) throw new Error(`${dirName}/SKILL.md: missing --- frontmatter block`)
  const [, frontmatter, body] = match

  const nameMatch = frontmatter.match(/^name:\s*(.+)$/m)
  const descMatch = frontmatter.match(/^description:\s*(.+)$/m)
  if (!nameMatch || !descMatch) throw new Error(`${dirName}/SKILL.md: frontmatter needs both name and description`)

  const name = nameMatch[1].trim()
  if (name !== dirName) throw new Error(`${dirName}/SKILL.md: frontmatter name "${name}" must match its directory name`)

  return { name, description: descMatch[1].trim(), instructions: body.trim() }
}

const dirs = readdirSync(SKILLS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort()

const skills = dirs.map((dirName) => parseSkillMd(readFileSync(join(SKILLS_DIR, dirName, 'SKILL.md'), 'utf-8'), dirName))

const lines: string[] = []
lines.push(`// GENERATED by scripts/build-skills.ts from docs/BayMax/skills/*/SKILL.md on ${new Date().toISOString().slice(0, 10)}.`)
lines.push('// Do not edit by hand — edit the SKILL.md files and rerun `npm run build:skills` instead.')
lines.push('')
lines.push('export interface MaxSkill {')
lines.push('  name: string')
lines.push('  description: string')
lines.push('  instructions: string')
lines.push('}')
lines.push('')
lines.push('export const maxSkills: Record<string, MaxSkill> = {')
for (const skill of skills) {
  lines.push(`  ${JSON.stringify(skill.name)}: {`)
  lines.push(`    name: ${JSON.stringify(skill.name)},`)
  lines.push(`    description: ${JSON.stringify(skill.description)},`)
  lines.push(`    instructions: ${JSON.stringify(skill.instructions)},`)
  lines.push('  },')
}
lines.push('}')
lines.push('')

writeFileSync(OUT_FILE, lines.join('\n'))
console.log(`Wrote ${skills.length} skill(s) to ${OUT_FILE}: ${skills.map((s) => s.name).join(', ')}`)
