// Writes src/data/bannerHistory.ts: every Banner term (Fall 2024 to Winter 2027, Spring xx05 and
// Summer xx07 kept apart) in which each CMPT, MATH and STAT course had a section. Input is a dump of
// one line per course, "CMPT432  202501", made per term with subjectCourseNumbers() in
// api/_banner.ts (the planner audit's perterm.ts). Run:
// node --experimental-strip-types scripts/build-banner-history.ts <perterm.out>
import { readFileSync, writeFileSync } from 'node:fs'

const src = process.argv[2]
if (!src) throw new Error('usage: build-banner-history.ts <perterm.out>')
const rows: [string, string[]][] = []
const terms = new Set<string>()
for (const line of readFileSync(src, 'utf8').split('\n')) {
  const course = line.match(/^([A-Z]+\d{3})\s+(\d{6}(?:\s+\d{6})*)\s*$/)
  if (course) rows.push([course[1], course[2].split(/\s+/)])
  const header = line.match(/^[A-Z]+ (\d{6}) \d+$/)
  if (header) terms.add(header[1])
}
rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
const termList = [...terms].sort()
const out = `// GENERATED by scripts/build-banner-history.ts from USask's class search (banner.usask.ca), read
// per term on 2026-09-27. Do not edit by hand — rerun the script on a fresh dump instead.
//
// The Banner terms in which each CMPT, MATH and STAT course had at least one section, Spring (xx05)
// and Summer (xx07) apart. A course in the catalogue with no entry had no section in any of them.
// src/data/offeringConfidence.ts reads the cadence (every year, some years, never) from this.

/** Every term the dump covers, oldest first. */
export const BANNER_HISTORY_TERMS = [${termList.map((t) => `'${t}'`).join(', ')}] as const

/** Subjects the dump covers; a course of another subject is simply not in it. */
export const BANNER_HISTORY_SUBJECTS = ['CMPT', 'MATH', 'STAT'] as const

export const bannerHistory: Record<string, string[]> = {
${rows.map(([c, t]) => `  ${c}: [${t.map((x) => `'${x}'`).join(', ')}],`).join('\n')}
}
`
writeFileSync(new URL('../src/data/bannerHistory.ts', import.meta.url), out)
console.log(`bannerHistory.ts: ${rows.length} courses over ${termList.length} terms`)
