// Builds src/data/breadth.ts: which Arts & Science program types and requirement attributes each
// course carries, from saved USask class-search (Banner) attribute dumps.
// Run: node --experimental-strip-types scripts/build-breadth.ts <dump-dir>
//
// <dump-dir> holds one a_<ATTR>.json per attribute: the JSON body of Banner's
//   GET https://banner.usask.ca/StudentRegistrationSsb/ssb/searchResults/searchResults?txt_attribute=<ATTR>&txt_term=<TERM>&pageOffset=0&pageMaxSize=500
// after opening a session (GET classSearch/classSearch, then POST term/search?mode=search with
// term=<TERM>). Save one file per attribute and term (a_HUM.json, a_HUM-202701.json, ...): every file
// named a_*.json is read, and each row's sectionAttributes are unioned, so a section that carries
// several attributes (ENG 113: HUM and ELWR) fills them all whichever search found it.
//
// If <dump-dir> also holds bsc-4-computer-science.txt (the program page's text), its C2 junior
// panels are added as types too: the page lists junior Fine Arts, Humanities and Social Science
// courses by name, and a course not running in a dumped term has no Banner row to carry them.
//
// ARNP ("Arts and Sci No Program Type") and NASC are not mapped: neither makes a course breadth.
// QRRQ merges the B.A. and B.Sc. Quantitative Reasoning lists, so it is kept only for the B.Sc. list
// (programs.usask.ca/arts-and-science/policies.php, "for B.Sc. and B.A.&Sc. programs").
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

type BreadthType = 'HUM' | 'SOCS' | 'FNAR' | 'SCIE' | 'ELWR' | 'ILRQ' | 'QRRQ'
const TYPES: BreadthType[] = ['HUM', 'SOCS', 'FNAR', 'SCIE', 'ELWR', 'ILRQ', 'QRRQ']

const BSC_QR = new Set([
  'MATH110', 'MATH116', 'MATH123', 'MATH124', 'MATH125', 'MATH133', 'MATH134', 'MATH163', 'MATH164', 'MATH176',
  'MATH177', 'STAT245', 'STAT246', 'PLSC214',
])

interface Row {
  term: string
  subjectCourse: string
  sectionAttributes?: { code: string }[]
}

const dir = process.argv[2]
if (!dir) throw new Error('usage: build-breadth.ts <dump-dir>')

const types = new Map<string, Set<BreadthType>>()
const add = (code: string, type: BreadthType) => {
  if (!/^[A-Z]{2,4}[1-4]\d\d$/.test(code)) return
  if (type === 'QRRQ' && !BSC_QR.has(code)) return
  if (!types.has(code)) types.set(code, new Set())
  types.get(code)!.add(type)
}

const terms = new Set<string>()
const files = readdirSync(dir).filter((f) => /^a_.*\.json$/.test(f)).sort()
for (const file of files) {
  const rows: Row[] = JSON.parse(readFileSync(join(dir, file), 'utf8')).data ?? []
  for (const row of rows) {
    terms.add(row.term)
    for (const attr of row.sectionAttributes ?? []) {
      if ((TYPES as string[]).includes(attr.code)) add(row.subjectCourse, attr.code as BreadthType)
    }
  }
}

let panels = 0
const pagePath = join(dir, 'bsc-4-computer-science.txt')
if (existsSync(pagePath)) {
  const page = readFileSync(pagePath, 'utf8')
  const c2 = page.slice(page.indexOf(' C2 Breadth Requirement (9 credit units)\n Choose'), page.indexOf(' C3 Cognate Requirement (15-18 credit units)\n Junior'))
  const PANEL: Record<string, BreadthType | null> = {
    'Fine Arts': 'FNAR',
    Humanities: 'HUM',
    'Social Science': 'SOCS',
    'Courses with No Program Type': null,
  }
  let current: BreadthType | null = null
  for (const line of c2.split('\n').map((l) => l.trim())) {
    if (line in PANEL) current = PANEL[line]
    const m = line.match(/^([A-Z]{2,4}) (\d{3})\.\d$/)
    if (m && current) {
      add(m[1] + m[2], current)
      panels++
    }
  }
}

const byType = TYPES.map((type) => {
  const codes = [...types].filter(([, set]) => set.has(type)).map(([code]) => code).sort()
  const lines: string[] = []
  for (let i = 0; i < codes.length; i += 12) lines.push(codes.slice(i, i + 12).join(' '))
  return `  ${type}: \`\n    ${lines.join('\n    ')}\n  \`,`
})

const termList = [...terms].sort().join(', ')
const today = new Date().toISOString().slice(0, 10)
const out = `// GENERATED by scripts/build-breadth.ts on ${today}. Do not edit by hand — rerun the script instead.
//
// Source: USask class search (Banner) section attributes,
// https://banner.usask.ca/StudentRegistrationSsb/ssb/searchResults/searchResults?txt_attribute=<ATTR>
// (HUM, SOCS, FNAR, SCIE, ELWR, QRRQ, ARNP, NASC searched; ILRQ read off the same sections), term(s)
// ${termList}, dumped 2026-09-26. Plus the junior Fine Arts, Humanities and Social Science panels of
// https://programs.usask.ca/arts-and-science/computer-science/bsc-4-computer-science.php (2026-27), which
// repeat the college's junior lists (https://programs.usask.ca/arts-and-science/policies.php).
// QRRQ is kept only for the B.Sc. Quantitative Reasoning list; ARNP is not breadth and not mapped.
//
// Attributes live on sections, so a senior course that didn't run in a dumped term has no entry.
// Regenerate: dump more terms (202701, 202705, 202707, ...) into the directory and run
//   node --experimental-strip-types scripts/build-breadth.ts <dump-dir>

import type { BreadthType } from './degrees/types.js'

const LISTS: Record<BreadthType, string> = {
${byType.join('\n')}
}

/** Program types and requirement attributes by course code: breadth.PHIL232 = ['HUM']. */
export const breadth: Record<string, BreadthType[]> = {}
for (const type of Object.keys(LISTS) as BreadthType[]) {
  for (const code of LISTS[type].split(/\\s+/)) if (code) (breadth[code] ??= []).push(type)
}
`
writeFileSync(new URL('../src/data/breadth.ts', import.meta.url), out)
console.log(
  `breadth.ts: ${types.size} courses from ${files.length} dumps (terms ${termList}) + ${panels} page panel codes; ` +
    TYPES.map((t) => `${t} ${[...types.values()].filter((s) => s.has(t)).length}`).join(', '),
)
