#!/usr/bin/env bash
# Regenerate the iOS + Android app icons and splash marks from resources/mark.svg.
# Requires rsvg-convert (brew install librsvg) and ImageMagick (`magick`, brew install imagemagick).
#
# Usage:
#   npm run cap:assets
#
# Icon: the mark in Old Lace on a Cherry Rose field.
# Splash: the mark in Cherry Rose on Old Lace. The mark's full 64-unit box is drawn at 96pt/dp and
# centred in the whole screen, so the web app's intro can pick it up in exactly the same place.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MARK="$ROOT/resources/mark.svg"
CHERRY='#982649'
LACE='#FFF8EB'
SPLASH_MARK=96
IOS_ASSETS="$ROOT/ios/App/App/Assets.xcassets"
RES="$ROOT/android/app/src/main/res"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

for tool in rsvg-convert magick perl bc; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Missing $tool: install it (brew install librsvg imagemagick) and retry." >&2
    exit 1
  fi
done

# The mark's drawing without its <svg> wrapper, recoloured.
mark_body() {
  perl -0pe 's/.*?<svg[^>]*>//s; s/<\/svg>\s*$//s; s/<!--.*?-->//gs' "$MARK" | sed "s/#982649/$1/g"
}

# compose WIDTH HEIGHT BACKGROUND_SVG MARK_COLOUR MARK_SIZE OUT.png
# Draws the background, then the mark's 64-unit box at MARK_SIZE px, centred.
compose() {
  local w=$1 h=$2 bg=$3 colour=$4 size=$5 out=$6
  local x y
  x=$(echo "($w - $size) / 2" | bc -l)
  y=$(echo "($h - $size) / 2" | bc -l)
  cat > "$TMP/compose.svg" <<EOF
<svg xmlns="http://www.w3.org/2000/svg" width="$w" height="$h" viewBox="0 0 $w $h">
$bg
<svg x="$x" y="$y" width="$size" height="$size" viewBox="0 0 64 64">$(mark_body "$colour")</svg>
</svg>
EOF
  mkdir -p "$(dirname "$out")"
  rsvg-convert -w "$w" -h "$h" "$TMP/compose.svg" -o "$out"
}

fill() { echo "<rect width=\"100%\" height=\"100%\" fill=\"$1\"/>"; }

if [[ ! -f "$MARK" ]]; then
  echo "Missing $MARK (the StudyMax mark every icon and splash is drawn from)." >&2
  exit 1
fi
echo "Using mark: $MARK"

# --- iOS ---------------------------------------------------------------------------------------
# App icon: exactly 1024x1024 with no alpha channel (App Store and ad hoc installs reject alpha).
compose 1024 1024 "$(fill "$CHERRY")" "$LACE" 640 "$TMP/icon.png"
magick "$TMP/icon.png" -background "$CHERRY" -alpha remove -alpha off -strip \
  "$IOS_ASSETS/AppIcon.appiconset/AppIcon-512@2x.png"

# Launch screen mark, shown by LaunchScreen.storyboard in a fixed 96pt image view.
rm -rf "$IOS_ASSETS/Splash.imageset"
SPLASH_SET="$IOS_ASSETS/SplashMark.imageset"
mkdir -p "$SPLASH_SET"
for scale in 1 2 3; do
  px=$((SPLASH_MARK * scale))
  suffix=$([[ $scale == 1 ]] && echo "" || echo "@${scale}x")
  compose "$px" "$px" "" "$CHERRY" "$px" "$SPLASH_SET/splash-mark$suffix.png"
done
cat > "$SPLASH_SET/Contents.json" <<'EOF'
{
  "images" : [
    { "filename" : "splash-mark.png", "idiom" : "universal", "scale" : "1x" },
    { "filename" : "splash-mark@2x.png", "idiom" : "universal", "scale" : "2x" },
    { "filename" : "splash-mark@3x.png", "idiom" : "universal", "scale" : "3x" }
  ],
  "info" : { "author" : "xcode", "version" : 1 }
}
EOF

# --- Android -----------------------------------------------------------------------------------
# Adaptive icon: Cherry Rose background colour + the Old Lace mark as a vector foreground. The
# vectors below repeat resources/mark.svg's two shapes (ring arc and dot); keep them in step.
RING='M32,12 A20,20 0 1,1 12.3,28.53'
DOT='M32,25.5 A6.5,6.5 0 1,1 32,38.5 A6.5,6.5 0 1,1 32,25.5 Z'

# vector_mark NAME COLOUR SCALE  (108x108 viewport, mark centred at 54,54)
vector_mark() {
  local name=$1 colour=$2 scale=$3
  local shift
  shift=$(echo "54 - 32 * $scale" | bc -l | sed 's/^\./0./; s/0*$//; s/\.$//')
  cat > "$RES/drawable/$name.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-native-assets.sh from resources/mark.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:scaleX="$scale"
        android:scaleY="$scale"
        android:translateX="$shift"
        android:translateY="$shift">
        <path
            android:pathData="$RING"
            android:strokeColor="$colour"
            android:strokeWidth="8"
            android:strokeLineCap="round" />
        <path
            android:pathData="$DOT"
            android:fillColor="$colour" />
    </group>
</vector>
EOF
}

mkdir -p "$RES/drawable" "$RES/mipmap-anydpi-v26" "$RES/values"
# Foreground: the ring's outer edge spans 46dp of the 108dp canvas, well inside the 66dp safe zone.
vector_mark ic_launcher_foreground "$LACE" 0.9583
# Android 12+ splash icon: the platform draws it at 288dp, so 36 of 108 units is the same 96dp
# mark box as iOS.
vector_mark splash_icon "$CHERRY" 0.5625

# Capacitor's template icons would otherwise shadow ours.
rm -f "$RES/drawable-v24/ic_launcher_foreground.xml" "$RES/drawable/ic_launcher_background.xml"
rm -f "$RES"/mipmap-*/ic_launcher_foreground.png
rmdir "$RES/drawable-v24" 2>/dev/null || true

for name in ic_launcher ic_launcher_round; do
  cat > "$RES/mipmap-anydpi-v26/$name.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
EOF
done
cat > "$RES/values/ic_launcher_background.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">$CHERRY</color>
</resources>
EOF

# Legacy launcher icons (API 24-25): a rounded square and a circle, mark in Old Lace.
gen_legacy() {
  local folder=$1 px=$2
  local r inset mark
  inset=$(echo "$px * 0.04" | bc -l)
  r=$(echo "$px * 0.2" | bc -l)
  mark=$(echo "$px * 0.58" | bc -l)
  local side
  side=$(echo "$px - 2 * $inset" | bc -l)
  compose "$px" "$px" "<rect x=\"$inset\" y=\"$inset\" width=\"$side\" height=\"$side\" rx=\"$r\" fill=\"$CHERRY\"/>" \
    "$LACE" "$mark" "$RES/$folder/ic_launcher.png"
  compose "$px" "$px" "<circle cx=\"$(echo "$px / 2" | bc -l)\" cy=\"$(echo "$px / 2" | bc -l)\" r=\"$(echo "$px * 0.46" | bc -l)\" fill=\"$CHERRY\"/>" \
    "$LACE" "$mark" "$RES/$folder/ic_launcher_round.png"
}
gen_legacy mipmap-mdpi 48
gen_legacy mipmap-hdpi 72
gen_legacy mipmap-xhdpi 96
gen_legacy mipmap-xxhdpi 144
gen_legacy mipmap-xxxhdpi 192

# Splash drawables the plugin falls back to: Old Lace with the 96dp mark, at each density.
gen_splash() {
  local folder=$1 w=$2 h=$3 density=$4
  compose "$w" "$h" "$(fill "$LACE")" "$CHERRY" "$(echo "$SPLASH_MARK * $density" | bc -l)" "$RES/$folder/splash.png"
}
gen_splash drawable 480 320 1
for orient in port land; do
  for spec in "mdpi 320 480 1" "hdpi 480 800 1.5" "xhdpi 720 1280 2" "xxhdpi 960 1600 3" "xxxhdpi 1280 1920 4"; do
    read -r d w h density <<<"$spec"
    if [[ $orient == land ]]; then gen_splash "drawable-land-$d" "$h" "$w" "$density"
    else gen_splash "drawable-port-$d" "$w" "$h" "$density"; fi
  done
done

echo "Done: iOS AppIcon + SplashMark, Android adaptive/legacy icons + splash updated."
