#!/usr/bin/env bash
# Regenerates the native app icons and splash screens from the approved StudyMax brand pack.
#
#   App icons  copied exactly as supplied: resources/brand/ios/AppIcon.appiconset (default, dark and
#              tinted) and resources/brand/android/res (adaptive, themed monochrome and legacy sizes).
#   Splash     flat Old Lace, nothing else: the first frame of the in-app intro, which is where the S
#              ignites. The S appears once, in the intro, so it never blinks between the native
#              launch screen, Capacitor's splash and the web view.
#
# Requires rsvg-convert and python3 (macOS: brew install librsvg).
# Usage: npm run cap:assets

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MARK="$ROOT/resources/mark.svg"
BRAND="$ROOT/resources/brand"
LACE='#FFF8EB'
BERRY='#982649'
INK='#12262B'
SPLASH_MARK=176
# The symbol's square box in resources/mark.svg, and the path inside it.
BOX_X=-45
BOX_Y=-36
BOX=362
IOS_ASSETS="$ROOT/ios/App/App/Assets.xcassets"
RES="$ROOT/android/app/src/main/res"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

for tool in rsvg-convert python3; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Missing $tool: install it and retry." >&2
    exit 1
  fi
done
for f in "$MARK" "$BRAND/approved-A2-path.json" "$BRAND/ios/AppIcon.appiconset/Contents.json" "$BRAND/android/res"; do
  if [[ ! -e "$f" ]]; then
    echo "Missing $f (part of the brand pack every icon and splash comes from)." >&2
    exit 1
  fi
done

SYMBOL="$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['d'])" "$BRAND/approved-A2-path.json")"

# ── iOS ──────────────────────────────────────────────────────────────────────────────────────────

rm -rf "$IOS_ASSETS/AppIcon.appiconset"
cp -R "$BRAND/ios/AppIcon.appiconset" "$IOS_ASSETS/"

# The launch storyboard is flat Old Lace; it no longer draws an image.
rm -rf "$IOS_ASSETS/SplashMark.imageset"

# ── Android ──────────────────────────────────────────────────────────────────────────────────────

# Launcher icons as supplied; AndroidManifest.xml points at @mipmap/studymax_launcher(_round).
cp -R "$BRAND/android/res/." "$RES/"
# The earlier generated set, which nothing references any more.
rm -f "$RES"/mipmap-*/ic_launcher.png "$RES"/mipmap-*/ic_launcher_round.png "$RES"/mipmap-*/ic_launcher_foreground.png
rm -f "$RES/mipmap-anydpi-v26/ic_launcher.xml" "$RES/mipmap-anydpi-v26/ic_launcher_round.xml"
rm -f "$RES/drawable/ic_launcher_foreground.xml" "$RES/drawable/ic_launcher_background.xml" "$RES/values/ic_launcher_background.xml"
rm -rf "$RES/drawable-v24"

# Android 12+ requires a splash icon; a transparent one leaves the flat Old Lace ground.
cat > "$RES/drawable/splash_icon.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-native-assets.sh. Transparent on purpose: the S ignites in the app. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="@android:color/transparent" />
    <size android:width="108dp" android:height="108dp" />
</shape>
EOF

# The splash drawables the plugin falls back to before Android 12: the same flat Old Lace.
gen_splash() {
  local folder=$1 w=$2 h=$3
  mkdir -p "$RES/$folder"
  cat > "$TMP/splash.svg" <<EOF
<svg xmlns="http://www.w3.org/2000/svg" width="$w" height="$h"><rect width="100%" height="100%" fill="$LACE"/></svg>
EOF
  rsvg-convert -w "$w" -h "$h" "$TMP/splash.svg" -o "$RES/$folder/splash.png"
}
gen_splash drawable 480 320 1
for orient in port land; do
  for spec in "mdpi 320 480 1" "hdpi 480 800 1.5" "xhdpi 720 1280 2" "xxhdpi 960 1600 3" "xxxhdpi 1280 1920 4"; do
    read -r d w h density <<<"$spec"
    if [[ $orient == land ]]; then gen_splash "drawable-land-$d" "$h" "$w" "$density"
    else gen_splash "drawable-port-$d" "$w" "$h" "$density"; fi
  done
done

echo "Done: iOS AppIcon, Android launcher icons, and flat Old Lace splash drawables updated."
