// Which terms each course actually runs in, from USask's class search (Banner), and regenerates
// src/data/offerings.ts. Run: npx tsx --experimental-loader ./scripts/_resolve-ts-loader.mjs scripts/scrape-offerings.ts   (about ten minutes: it's polite)
//
// Two academic years are read, so a course offered every other year still has a season. Spring and
// Summer are one season to the planner. A course the search never shows gets no entry, and the
// planner then places it anywhere, as before.
import { writeFileSync } from 'node:fs'
import { subjectCourseNumbers } from '../api/_banner.ts'
import { courseInfo } from '../src/data/prereqs.ts'
import { programs } from '../src/data/programs/index.ts'

type Season = 'Fall' | 'Winter' | 'Spring/Summer'

// 2025–26 and 2026–27. Spring/Summer 2027 isn't published until the new year, so 2025 and 2026 stand in.
const TERMS: { code: string; season: Season }[] = [
  { code: '202509', season: 'Fall' },
  { code: '202609', season: 'Fall' },
  { code: '202601', season: 'Winter' },
  { code: '202701', season: 'Winter' },
  { code: '202505', season: 'Spring/Summer' },
  { code: '202507', season: 'Spring/Summer' },
  { code: '202605', season: 'Spring/Summer' },
  { code: '202607', season: 'Spring/Summer' },
]

/** Every course the planner can schedule: requirement lists plus the prerequisite graph. */
const codes = new Set<string>(Object.keys(courseInfo))
for (const program of programs)
  for (const spec of program.specializations) for (const group of spec.requirements) group.courses.forEach((c) => codes.add(c))
const subjects = [...new Set([...codes].map((c) => c.match(/^[A-Z]+/)?.[0]).filter((s): s is string => !!s))].sort()

const seasons = new Map<string, Set<Season>>()
let done = 0
for (const subject of subjects) {
  for (const term of TERMS) {
    try {
      for (const number of await subjectCourseNumbers(term.code, subject)) {
        const code = `${subject}${number}`
        if (!codes.has(code)) continue
        if (!seasons.has(code)) seasons.set(code, new Set())
        seasons.get(code)!.add(term.season)
      }
    } catch (error) {
      console.warn(`  ${subject} ${term.code}: ${(error as Error).message}`)
    }
    await new Promise((r) => setTimeout(r, 400))
  }
  done++
  console.log(`${subject} (${done}/${subjects.length})`)
}

const ORDER: Season[] = ['Fall', 'Winter', 'Spring/Summer']
const entries = [...seasons]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, set]) => `  ${code}: [${ORDER.filter((s) => set.has(s)).map((s) => `'${s}'`).join(', ')}],`)

const today = new Date().toISOString().slice(0, 10)
writeFileSync(
  'src/data/offerings.ts',
  `// GENERATED by scripts/scrape-offerings.ts from USask's class search (banner.usask.ca) on ${today}.
// Do not edit by hand — rerun the scraper instead.
//
// The seasons each course ran in across 2025–26 and 2026–27 (Spring/Summer: 2025 and 2026). A course
// with no entry wasn't found in those terms; the planner places it anywhere rather than nowhere.

import type { Season } from '../lib/plan.ts'

export const OFFERINGS_SOURCE = "USask's class search, 2025–26 and 2026–27"

export const offerings: Record<string, Season[]> = {
${entries.join('\n')}
}
`,
)
console.log(`wrote ${entries.length} of ${codes.size} courses to src/data/offerings.ts`)
