// src/data/prereqs.ts is now generated by scripts/scrape-catalogue.ts, from the catalogue's JSON API
// (which also carries the offered term, corequisites and credit-unit prerequisites). Running this
// file runs that scraper.
//
// What stays here is the subject-search HTML reader scripts/scrape-courses.ts still uses for the
// course-search catalogue (src/data/courses.ts).

function decode(html: string): string {
  return html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&[a-z]+;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

export interface ScrapedCourse {
  code: string
  title: string
  creditUnits: number
  /** Verbatim catalogue text. Empty string means the catalogue lists no prerequisite. */
  prerequisiteText: string
}

/** Pulls one record per course out of a subject search results page. */
export function parseSubjectPage(html: string, subject: string): ScrapedCourse[] {
  const courses: ScrapedCourse[] = []
  // Each course starts with an <h4> linking to /SUBJ-NUM; the block runs to the next one.
  const blocks = html.split(/(?=<h4>\s*<a href="https:\/\/catalogue\.usask\.ca\/[A-Z]+-\d+")/i).slice(1)

  for (const block of blocks) {
    const heading = block.match(
      new RegExp(`${subject}\\s+(\\d+)\\.(\\d+(?:\\.\\d+)?)\\s*:\\s*([^<]+)`, 'i'),
    )
    if (!heading) continue

    const prereq = block.match(/<b>\s*Prerequisite\(s\)\s*:\s*<\/b>([\s\S]*?)(?:<br\s*\/?>|<\/p>)/i)

    courses.push({
      code: `${subject}${heading[1]}`,
      title: decode(heading[3]),
      creditUnits: Number(heading[2]),
      prerequisiteText: prereq ? decode(prereq[1]).replace(/\.$/, '') : '',
    })
  }

  return courses
}

if (process.argv[1]?.endsWith('scrape-prereqs.ts')) {
  console.log('scrape-prereqs.ts is retired: running scripts/scrape-catalogue.ts instead.\n')
  const { main } = await import('./scrape-catalogue.ts')
  await main()
}
